version: '3.8'

services:
  express:
    image: backend-dev
    build:
      context: .
      dockerfile: dev.Dockerfile
    ports:
    - 3000:3000
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'admin'
      MONGO_INITDB_ROOT_PASSWORD: 'strongestPasswordPfft'
      MONGO_INITDB_DATABASE: 'the_database'
      REDIS_URL: redis://redis:6379
      MONGO_URL: mongodb://admin:strongestPasswordPfft@mongo:27017/the_database
    volumes:
    - ./:/usr/src/app
    depends_on:
    - mongo
    - redis
    container_name: backend

  mongo:
    image: mongo
    ports:
     - 3456:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'admin'
      MONGO_INITDB_ROOT_PASSWORD: 'strongestPasswordPfft'
      MONGO_INITDB_DATABASE: the_database
    volumes:
    - ./mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    - ./mongo_data:/data/db
    container_name: mongo

  redis:
    image: redis
    ports:
    - 6378:6379
    command: ['redis-server','--appendonly', 'yes']
    volumes:
    - ./redis_data:/data
    container_name: redis

volumes:
  mongo_data:
